[{
  "id": 1,
  "client_since": "310M - B.C.",
  "first_name": "Mirtha",
  "last_name": "Legrand",
  "email": null,
  "country": "Pangea",
  "likes_simpson": "no",
  "is_flat_earther": false
}, {
  "id": 2,
  "client_since": "9/29/2021",
  "first_name": "Bryanty",
  "last_name": "Dami",
  "email": "bdami1@huffingtonpost.com",
  "country": "Israel",
  "likes_simpson": "a lot",
  "is_flat_earther": false
}, {
  "id": 3,
  "client_since": "8/3/2021",
  "first_name": "Jacinthe",
  "last_name": "Arrigucci",
  "email": "jarrigucci2@mapquest.com",
  "country": "China",
  "likes_simpson": "no",
  "is_flat_earther": true
}, {
  "id": 4,
  "client_since": "2/20/2022",
  "first_name": "Philly",
  "last_name": "Bosenworth",
  "email": "pbosenworth3@loc.gov",
  "country": "Philippines",
  "likes_simpson": "no",
  "is_flat_earther": false
}, {
  "id": 5,
  "client_since": "1/17/2022",
  "first_name": "Danette",
  "last_name": "Corbin",
  "email": "dcorbin4@discuz.net",
  "country": "Vietnam",
  "likes_simpson": "just a bit",
  "is_flat_earther": true
}, {
  "id": 6,
  "client_since": "9/30/2021",
  "first_name": "Allx",
  "last_name": "Strickland",
  "email": "astrickland5@jiathis.com",
  "country": "Russia",
  "likes_simpson": "no",
  "is_flat_earther": false
}, {
  "id": 7,
  "client_since": "2/7/2022",
  "first_name": "Dorise",
  "last_name": "Engelbrecht",
  "email": "dengelbrecht6@istockphoto.com",
  "country": "China",
  "likes_simpson": "a lot",
  "is_flat_earther": false
}, {
  "id": 8,
  "client_since": "5/26/2022",
  "first_name": "Horten",
  "last_name": "Neiland",
  "email": "hneiland7@t-online.de",
  "country": "Portugal",
  "likes_simpson": "no",
  "is_flat_earther": true
}, {
  "id": 9,
  "client_since": "6/27/2021",
  "first_name": "Rosemarie",
  "last_name": "Markwell",
  "email": "rmarkwell8@pinterest.com",
  "country": "Nigeria",
  "likes_simpson": "just a bit",
  "is_flat_earther": true
}, {
  "id": 10,
  "client_since": "1/14/2022",
  "first_name": "Avivah",
  "last_name": "Everleigh",
  "email": "aeverleigh9@netscape.com",
  "country": "Philippines",
  "likes_simpson": "no",
  "is_flat_earther": false
}, {
  "id": 11,
  "client_since": "11/14/2021",
  "first_name": "Kevan",
  "last_name": "Di Bartolommeo",
  "email": "kdibartolommeoa@live.com",
  "country": "France",
  "likes_simpson": "no",
  "is_flat_earther": false
}, {
  "id": 12,
  "client_since": "2/22/2022",
  "first_name": "Raimundo",
  "last_name": "Zavattiero",
  "email": "rzavattierob@hc360.com",
  "country": "China",
  "likes_simpson": "just a bit",
  "is_flat_earther": false
}, {
  "id": 13,
  "client_since": "3/8/2022",
  "first_name": "Vite",
  "last_name": "Hardey",
  "email": "vhardeyc@booking.com",
  "country": "Thailand",
  "likes_simpson": "just a bit",
  "is_flat_earther": false
}, {
  "id": 14,
  "client_since": "12/8/2021",
  "first_name": "Clemmie",
  "last_name": "Halwell",
  "email": "chalwelld@webnode.com",
  "country": "Mexico",
  "likes_simpson": "just a bit",
  "is_flat_earther": true
}, {
  "id": 15,
  "client_since": "11/11/2021",
  "first_name": "Lilith",
  "last_name": "Rookes",
  "email": "lrookese@elpais.com",
  "country": "Benin",
  "likes_simpson": "just a bit",
  "is_flat_earther": true
}, {
  "id": 16,
  "client_since": "10/31/2021",
  "first_name": "Sheila-kathryn",
  "last_name": "Gilberthorpe",
  "email": "sgilberthorpef@cbsnews.com",
  "country": "Indonesia",
  "likes_simpson": "just a bit",
  "is_flat_earther": false
}, {
  "id": 17,
  "client_since": "12/11/2021",
  "first_name": "Durand",
  "last_name": "Benstead",
  "email": "dbensteadg@pcworld.com",
  "country": "French Polynesia",
  "likes_simpson": "no",
  "is_flat_earther": false
}, {
  "id": 18,
  "client_since": "2/9/2022",
  "first_name": "Maridel",
  "last_name": "Lie",
  "email": "mlieh@usda.gov",
  "country": "Philippines",
  "likes_simpson": "a lot",
  "is_flat_earther": true
}, {
  "id": 19,
  "client_since": "12/6/2021",
  "first_name": "Teresa",
  "last_name": "Smitton",
  "email": "tsmittoni@clickbank.net",
  "country": "China",
  "likes_simpson": "just a bit",
  "is_flat_earther": false
}, {
  "id": 20,
  "client_since": "9/21/2021",
  "first_name": "Yasmin",
  "last_name": "Shadbolt",
  "email": "yshadboltj@cafepress.com",
  "country": "China",
  "likes_simpson": "a lot",
  "is_flat_earther": false
}, {
  "id": 21,
  "client_since": "1/4/2022",
  "first_name": "Joanie",
  "last_name": "Duchenne",
  "email": "jduchennek@merriam-webster.com",
  "country": "China",
  "likes_simpson": "a lot",
  "is_flat_earther": false
}, {
  "id": 22,
  "client_since": "10/30/2021",
  "first_name": "Sapphire",
  "last_name": "Arnett",
  "email": "sarnettl@fda.gov",
  "country": "Canada",
  "likes_simpson": "a lot",
  "is_flat_earther": false
}, {
  "id": 23,
  "client_since": "2/6/2022",
  "first_name": "Keane",
  "last_name": "Fabler",
  "email": "kfablerm@w3.org",
  "country": "South Korea",
  "likes_simpson": "just a bit",
  "is_flat_earther": false
}, {
  "id": 24,
  "client_since": "11/11/2021",
  "first_name": "Ignatius",
  "last_name": "Bennoe",
  "email": "ibennoen@paypal.com",
  "country": "Indonesia",
  "likes_simpson": "just a bit",
  "is_flat_earther": true
}, {
  "id": 25,
  "client_since": "8/30/2021",
  "first_name": "Karel",
  "last_name": "Legonidec",
  "email": "klegonideco@4shared.com",
  "country": "Cameroon",
  "likes_simpson": "a lot",
  "is_flat_earther": true
}, {
  "id": 26,
  "client_since": "5/18/2022",
  "first_name": "Harrietta",
  "last_name": "Stapleford",
  "email": "hstaplefordp@tumblr.com",
  "country": "Portugal",
  "likes_simpson": "a lot",
  "is_flat_earther": true
}, {
  "id": 27,
  "client_since": "4/7/2022",
  "first_name": "Dwight",
  "last_name": "Bedding",
  "email": "dbeddingq@auda.org.au",
  "country": "Norway",
  "likes_simpson": "a lot",
  "is_flat_earther": true
}, {
  "id": 28,
  "client_since": "6/18/2021",
  "first_name": "Hunter",
  "last_name": "Kensley",
  "email": "hkensleyr@myspace.com",
  "country": "China",
  "likes_simpson": "no",
  "is_flat_earther": false
}, {
  "id": 29,
  "client_since": "4/30/2022",
  "first_name": "Jackie",
  "last_name": "Carlaw",
  "email": "jcarlaws@vistaprint.com",
  "country": "Nigeria",
  "likes_simpson": "no",
  "is_flat_earther": true
}, {
  "id": 30,
  "client_since": "1/25/2022",
  "first_name": "Wes",
  "last_name": "Frichley",
  "email": "wfrichleyt@drupal.org",
  "country": "Philippines",
  "likes_simpson": "just a bit",
  "is_flat_earther": false
}, {
  "id": 31,
  "client_since": "5/21/2022",
  "first_name": "Fairlie",
  "last_name": "Tredwell",
  "email": "ftredwellu@ebay.com",
  "country": "Dominican Republic",
  "likes_simpson": "a lot",
  "is_flat_earther": false
}, {
  "id": 32,
  "client_since": "11/10/2021",
  "first_name": "Martie",
  "last_name": "Stobbs",
  "email": "mstobbsv@archive.org",
  "country": "Colombia",
  "likes_simpson": "just a bit",
  "is_flat_earther": false
}, {
  "id": 33,
  "client_since": "9/8/2021",
  "first_name": "Dulce",
  "last_name": "Tomek",
  "email": "dtomekw@diigo.com",
  "country": "Philippines",
  "likes_simpson": "no",
  "is_flat_earther": true
}, {
  "id": 34,
  "client_since": "10/2/2021",
  "first_name": "Roth",
  "last_name": "Northover",
  "email": "rnorthoverx@usgs.gov",
  "country": "Indonesia",
  "likes_simpson": "just a bit",
  "is_flat_earther": false
}, {
  "id": 35,
  "client_since": "6/23/2021",
  "first_name": "Gert",
  "last_name": "Hawksworth",
  "email": "ghawksworthy@aboutads.info",
  "country": "Peru",
  "likes_simpson": "no",
  "is_flat_earther": true
}, {
  "id": 36,
  "client_since": "3/30/2022",
  "first_name": "Nelie",
  "last_name": "Ranyelld",
  "email": "nranyelldz@smh.com.au",
  "country": "Thailand",
  "likes_simpson": "just a bit",
  "is_flat_earther": true
}, {
  "id": 37,
  "client_since": "1/14/2022",
  "first_name": "Carin",
  "last_name": "Whiles",
  "email": "cwhiles10@latimes.com",
  "country": "Kazakhstan",
  "likes_simpson": "just a bit",
  "is_flat_earther": true
}, {
  "id": 38,
  "client_since": "11/14/2021",
  "first_name": "Noelyn",
  "last_name": "Shatliff",
  "email": "nshatliff11@nasa.gov",
  "country": "Argentina",
  "likes_simpson": "a lot",
  "is_flat_earther": false
}, {
  "id": 39,
  "client_since": "1/28/2022",
  "first_name": "Trixy",
  "last_name": "Stickland",
  "email": "tstickland12@pinterest.com",
  "country": "Kazakhstan",
  "likes_simpson": "a lot",
  "is_flat_earther": false
}, {
  "id": 40,
  "client_since": "12/16/2021",
  "first_name": "Rubetta",
  "last_name": "Plait",
  "email": "rplait13@sakura.ne.jp",
  "country": "Pakistan",
  "likes_simpson": "just a bit",
  "is_flat_earther": true
}, {
  "id": 41,
  "client_since": "4/19/2022",
  "first_name": "Ronalda",
  "last_name": "McOrkil",
  "email": "rmcorkil14@w3.org",
  "country": "France",
  "likes_simpson": "a lot",
  "is_flat_earther": true
}, {
  "id": 42,
  "client_since": "10/7/2021",
  "first_name": "Camellia",
  "last_name": "Dilloway",
  "email": "cdilloway15@cornell.edu",
  "country": "Pakistan",
  "likes_simpson": "a lot",
  "is_flat_earther": true
}, {
  "id": 43,
  "client_since": "2/25/2022",
  "first_name": "Correy",
  "last_name": "Shillam",
  "email": "cshillam16@independent.co.uk",
  "country": "Netherlands",
  "likes_simpson": "no",
  "is_flat_earther": false
}, {
  "id": 44,
  "client_since": "4/22/2022",
  "first_name": "Sarina",
  "last_name": "Summerly",
  "email": "ssummerly17@google.ru",
  "country": "Indonesia",
  "likes_simpson": "no",
  "is_flat_earther": true
}, {
  "id": 45,
  "client_since": "7/10/2021",
  "first_name": "Winne",
  "last_name": "Laite",
  "email": "wlaite18@reference.com",
  "country": "Lebanon",
  "likes_simpson": "just a bit",
  "is_flat_earther": false
}, {
  "id": 46,
  "client_since": "7/7/2021",
  "first_name": "Pall",
  "last_name": "Ivens",
  "email": "pivens19@indiegogo.com",
  "country": "Samoa",
  "likes_simpson": "a lot",
  "is_flat_earther": true
}, {
  "id": 47,
  "client_since": "3/6/2022",
  "first_name": "Eldredge",
  "last_name": "Hardisty",
  "email": "ehardisty1a@hud.gov",
  "country": "Indonesia",
  "likes_simpson": "just a bit",
  "is_flat_earther": false
}, {
  "id": 48,
  "client_since": "6/5/2021",
  "first_name": "Adriana",
  "last_name": "Toby",
  "email": "atoby1b@taobao.com",
  "country": "Afghanistan",
  "likes_simpson": "a lot",
  "is_flat_earther": true
}, {
  "id": 49,
  "client_since": "4/7/2022",
  "first_name": "Janot",
  "last_name": "Merill",
  "email": "jmerill1c@harvard.edu",
  "country": "Colombia",
  "likes_simpson": "no",
  "is_flat_earther": false
}, {
  "id": 50,
  "client_since": "9/27/2021",
  "first_name": "Othello",
  "last_name": "Coping",
  "email": "ocoping1d@so-net.ne.jp",
  "country": "Brazil",
  "likes_simpson": "no",
  "is_flat_earther": true
}, {
  "id": 51,
  "client_since": "11/7/2021",
  "first_name": "Hendrik",
  "last_name": "Fores",
  "email": "hfores1e@ow.ly",
  "country": "Russia",
  "likes_simpson": "a lot",
  "is_flat_earther": true
}, {
  "id": 52,
  "client_since": "5/30/2021",
  "first_name": "Fae",
  "last_name": "Baxendale",
  "email": "fbaxendale1f@multiply.com",
  "country": "Netherlands",
  "likes_simpson": "a lot",
  "is_flat_earther": false
}, {
  "id": 53,
  "client_since": "7/4/2021",
  "first_name": "Sherwin",
  "last_name": "Tabner",
  "email": "stabner1g@google.com.hk",
  "country": "Russia",
  "likes_simpson": "no",
  "is_flat_earther": true
}, {
  "id": 54,
  "client_since": "7/30/2021",
  "first_name": "Mayer",
  "last_name": "Drowsfield",
  "email": "mdrowsfield1h@hexun.com",
  "country": "Indonesia",
  "likes_simpson": "just a bit",
  "is_flat_earther": true
}, {
  "id": 55,
  "client_since": "4/2/2022",
  "first_name": "Papagena",
  "last_name": "Biggar",
  "email": "pbiggar1i@paginegialle.it",
  "country": "Russia",
  "likes_simpson": "no",
  "is_flat_earther": false
}, {
  "id": 56,
  "client_since": "5/8/2022",
  "first_name": "Theodore",
  "last_name": "Scones",
  "email": "tscones1j@studiopress.com",
  "country": "Sweden",
  "likes_simpson": "just a bit",
  "is_flat_earther": false
}, {
  "id": 57,
  "client_since": "3/17/2022",
  "first_name": "Avie",
  "last_name": "Burchill",
  "email": "aburchill1k@arizona.edu",
  "country": "Thailand",
  "likes_simpson": "no",
  "is_flat_earther": true
}, {
  "id": 58,
  "client_since": "7/10/2021",
  "first_name": "Jessamyn",
  "last_name": "Styche",
  "email": "jstyche1l@epa.gov",
  "country": "China",
  "likes_simpson": "no",
  "is_flat_earther": false
}, {
  "id": 59,
  "client_since": "7/17/2021",
  "first_name": "Briney",
  "last_name": "Bradder",
  "email": "bbradder1m@go.com",
  "country": "Indonesia",
  "likes_simpson": "no",
  "is_flat_earther": true
}, {
  "id": 60,
  "client_since": "6/30/2021",
  "first_name": "Ingaborg",
  "last_name": "Hubbert",
  "email": "ihubbert1n@mapquest.com",
  "country": "Yemen",
  "likes_simpson": "just a bit",
  "is_flat_earther": false
}, {
  "id": 61,
  "client_since": "12/23/2021",
  "first_name": "Hardy",
  "last_name": "Clague",
  "email": "hclague1o@ucoz.com",
  "country": "Russia",
  "likes_simpson": "a lot",
  "is_flat_earther": false
}, {
  "id": 62,
  "client_since": "4/25/2022",
  "first_name": "Allene",
  "last_name": "Rableau",
  "email": "arableau1p@apache.org",
  "country": "Colombia",
  "likes_simpson": "no",
  "is_flat_earther": false
}, {
  "id": 63,
  "client_since": "3/17/2022",
  "first_name": "Madella",
  "last_name": "McGarahan",
  "email": "mmcgarahan1q@wufoo.com",
  "country": "China",
  "likes_simpson": "no",
  "is_flat_earther": true
}, {
  "id": 64,
  "client_since": "3/15/2022",
  "first_name": "Mauricio",
  "last_name": "Mynett",
  "email": "mmynett1r@hatena.ne.jp",
  "country": "Paraguay",
  "likes_simpson": "just a bit",
  "is_flat_earther": true
}, {
  "id": 65,
  "client_since": "9/17/2021",
  "first_name": "Drucill",
  "last_name": "De Carteret",
  "email": "ddecarteret1s@sbwire.com",
  "country": "Brazil",
  "likes_simpson": "a lot",
  "is_flat_earther": false
}, {
  "id": 66,
  "client_since": "9/10/2021",
  "first_name": "Noak",
  "last_name": "Norquoy",
  "email": "nnorquoy1t@wikipedia.org",
  "country": "Ireland",
  "likes_simpson": "no",
  "is_flat_earther": true
}, {
  "id": 67,
  "client_since": "12/12/2021",
  "first_name": "Lyndsey",
  "last_name": "Zack",
  "email": "lzack1u@japanpost.jp",
  "country": "Greece",
  "likes_simpson": "no",
  "is_flat_earther": true
}, {
  "id": 68,
  "client_since": "11/24/2021",
  "first_name": "Johannah",
  "last_name": "MacInerney",
  "email": "jmacinerney1v@cnbc.com",
  "country": "Norway",
  "likes_simpson": "just a bit",
  "is_flat_earther": true
}, {
  "id": 69,
  "client_since": "3/12/2022",
  "first_name": "Con",
  "last_name": "Haddock",
  "email": "chaddock1w@ucoz.ru",
  "country": "Norway",
  "likes_simpson": "a lot",
  "is_flat_earther": true
}, {
  "id": 70,
  "client_since": "7/19/2021",
  "first_name": "Joanne",
  "last_name": "Langabeer",
  "email": "jlangabeer1x@photobucket.com",
  "country": "China",
  "likes_simpson": "no",
  "is_flat_earther": true
}, {
  "id": 71,
  "client_since": "7/7/2021",
  "first_name": "Ambur",
  "last_name": "Joselin",
  "email": "ajoselin1y@businessinsider.com",
  "country": "Pakistan",
  "likes_simpson": "no",
  "is_flat_earther": false
}, {
  "id": 72,
  "client_since": "12/3/2021",
  "first_name": "Betti",
  "last_name": "McCurry",
  "email": "bmccurry1z@ow.ly",
  "country": "China",
  "likes_simpson": "a lot",
  "is_flat_earther": true
}, {
  "id": 73,
  "client_since": "1/13/2022",
  "first_name": "Deanne",
  "last_name": "Bohlens",
  "email": "dbohlens20@columbia.edu",
  "country": "China",
  "likes_simpson": "a lot",
  "is_flat_earther": false
}, {
  "id": 74,
  "client_since": "5/27/2022",
  "first_name": "Hershel",
  "last_name": "Lago",
  "email": "hlago21@blogtalkradio.com",
  "country": "China",
  "likes_simpson": "a lot",
  "is_flat_earther": false
}, {
  "id": 75,
  "client_since": "4/6/2022",
  "first_name": "Brannon",
  "last_name": "Dorling",
  "email": "bdorling22@patch.com",
  "country": "Burkina Faso",
  "likes_simpson": "just a bit",
  "is_flat_earther": false
}, {
  "id": 76,
  "client_since": "5/24/2022",
  "first_name": "Daniel",
  "last_name": "Phinn",
  "email": "dphinn23@zimbio.com",
  "country": "Japan",
  "likes_simpson": "a lot",
  "is_flat_earther": false
}, {
  "id": 77,
  "client_since": "11/4/2021",
  "first_name": "Sallyann",
  "last_name": "Peppard",
  "email": "speppard24@upenn.edu",
  "country": "New Zealand",
  "likes_simpson": "just a bit",
  "is_flat_earther": true
}, {
  "id": 78,
  "client_since": "8/11/2021",
  "first_name": "Consalve",
  "last_name": "Oade",
  "email": "coade25@uiuc.edu",
  "country": "China",
  "likes_simpson": "no",
  "is_flat_earther": false
}, {
  "id": 79,
  "client_since": "5/30/2021",
  "first_name": "August",
  "last_name": "Walrond",
  "email": "awalrond26@51.la",
  "country": "Brazil",
  "likes_simpson": "just a bit",
  "is_flat_earther": true
}, {
  "id": 80,
  "client_since": "11/12/2021",
  "first_name": "Rivy",
  "last_name": "Nesbitt",
  "email": "rnesbitt27@vk.com",
  "country": "Thailand",
  "likes_simpson": "just a bit",
  "is_flat_earther": false
}, {
  "id": 81,
  "client_since": "10/6/2021",
  "first_name": "Gerhardt",
  "last_name": "Shackell",
  "email": "gshackell28@paypal.com",
  "country": "Indonesia",
  "likes_simpson": "no",
  "is_flat_earther": true
}, {
  "id": 82,
  "client_since": "12/3/2021",
  "first_name": "Darbee",
  "last_name": "Farmiloe",
  "email": "dfarmiloe29@chron.com",
  "country": "Portugal",
  "likes_simpson": "no",
  "is_flat_earther": false
}, {
  "id": 83,
  "client_since": "11/15/2021",
  "first_name": "Valida",
  "last_name": "Metts",
  "email": "vmetts2a@liveinternet.ru",
  "country": "Thailand",
  "likes_simpson": "no",
  "is_flat_earther": true
}, {
  "id": 84,
  "client_since": "11/5/2021",
  "first_name": "Emlynne",
  "last_name": "Jurick",
  "email": "ejurick2b@unblog.fr",
  "country": "Russia",
  "likes_simpson": "no",
  "is_flat_earther": true
}, {
  "id": 85,
  "client_since": "2/26/2022",
  "first_name": "Adria",
  "last_name": "Hounsom",
  "email": "ahounsom2c@ucoz.ru",
  "country": "Philippines",
  "likes_simpson": "a lot",
  "is_flat_earther": false
}, {
  "id": 86,
  "client_since": "8/10/2021",
  "first_name": "Basilio",
  "last_name": "Arnaut",
  "email": "barnaut2d@opera.com",
  "country": "Indonesia",
  "likes_simpson": "a lot",
  "is_flat_earther": true
}, {
  "id": 87,
  "client_since": "6/12/2021",
  "first_name": "Rube",
  "last_name": "Fewings",
  "email": "rfewings2e@hatena.ne.jp",
  "country": "China",
  "likes_simpson": "no",
  "is_flat_earther": true
}, {
  "id": 88,
  "client_since": "5/19/2022",
  "first_name": "Kim",
  "last_name": "Aysik",
  "email": "kaysik2f@google.nl",
  "country": "China",
  "likes_simpson": "just a bit",
  "is_flat_earther": true
}, {
  "id": 89,
  "client_since": "7/18/2021",
  "first_name": "Iorgos",
  "last_name": "Konzel",
  "email": "ikonzel2g@amazon.de",
  "country": "Indonesia",
  "likes_simpson": "just a bit",
  "is_flat_earther": false
}, {
  "id": 90,
  "client_since": "2/3/2022",
  "first_name": "Trevar",
  "last_name": "Clace",
  "email": "tclace2h@theglobeandmail.com",
  "country": "Pakistan",
  "likes_simpson": "no",
  "is_flat_earther": true
}, {
  "id": 91,
  "client_since": "3/26/2022",
  "first_name": "Kris",
  "last_name": "Leese",
  "email": "kleese2i@google.ca",
  "country": "Afghanistan",
  "likes_simpson": "just a bit",
  "is_flat_earther": false
}, {
  "id": 92,
  "client_since": "8/15/2021",
  "first_name": "Ebonee",
  "last_name": "Blincow",
  "email": "eblincow2j@washington.edu",
  "country": "Indonesia",
  "likes_simpson": "just a bit",
  "is_flat_earther": true
}, {
  "id": 93,
  "client_since": "2/15/2022",
  "first_name": "Priscella",
  "last_name": "Beatty",
  "email": "pbeatty2k@nature.com",
  "country": "Tajikistan",
  "likes_simpson": "a lot",
  "is_flat_earther": true
}, {
  "id": 94,
  "client_since": "6/2/2021",
  "first_name": "Ursulina",
  "last_name": "Murrells",
  "email": "umurrells2l@businessweek.com",
  "country": "Brazil",
  "likes_simpson": "just a bit",
  "is_flat_earther": true
}, {
  "id": 95,
  "client_since": "3/28/2022",
  "first_name": "Margalit",
  "last_name": "Kondrat",
  "email": "mkondrat2m@geocities.com",
  "country": "Poland",
  "likes_simpson": "no",
  "is_flat_earther": true
}, {
  "id": 96,
  "client_since": "6/24/2021",
  "first_name": "Adorne",
  "last_name": "Ghent",
  "email": "aghent2n@sohu.com",
  "country": "Russia",
  "likes_simpson": "a lot",
  "is_flat_earther": false
}, {
  "id": 97,
  "client_since": "5/13/2022",
  "first_name": "Pet",
  "last_name": "Furminger",
  "email": "pfurminger2o@mac.com",
  "country": "Philippines",
  "likes_simpson": "no",
  "is_flat_earther": false
}, {
  "id": 98,
  "client_since": "6/24/2021",
  "first_name": "Skippy",
  "last_name": "Rennie",
  "email": "srennie2p@friendfeed.com",
  "country": "Kazakhstan",
  "likes_simpson": "a lot",
  "is_flat_earther": true
}, {
  "id": 99,
  "client_since": "7/13/2021",
  "first_name": "Liane",
  "last_name": "Mullaly",
  "email": "lmullaly2q@geocities.jp",
  "country": "Morocco",
  "likes_simpson": "just a bit",
  "is_flat_earther": true
}, {
  "id": 100,
  "client_since": "8/31/2021",
  "first_name": "Lynde",
  "last_name": "Really",
  "email": "lreally2r@accuweather.com",
  "country": "China",
  "likes_simpson": "a lot",
  "is_flat_earther": true
}]